#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingapp
  namespace: arba
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
template:
metadata:
labels:
app: pingapp
spec:
  containers:
  - name: pingapp
    image: nicopaez/pingapp:3.0.0
    ports:
  - containerPort: 4567
    envFrom:
  - configMapRef:
    name: pingapp-config-env
